/** Declaration file generated by dts-gen */

declare module 'circomlibjs' {
  export class evmasm {
    constructor(...args: any[]);

    add(...args: any[]): void;

    addmod(...args: any[]): void;

    address(...args: any[]): void;

    and(...args: any[]): void;

    balance(...args: any[]): void;

    blockhash(...args: any[]): void;

    byte(...args: any[]): void;

    call(...args: any[]): void;

    callcode(...args: any[]): void;

    calldatacopy(...args: any[]): void;

    calldataload(...args: any[]): void;

    calldatasize(...args: any[]): void;

    caller(...args: any[]): void;

    callvalue(...args: any[]): void;

    codecopy(...args: any[]): void;

    codesize(...args: any[]): void;

    coinbase(...args: any[]): void;

    create(...args: any[]): void;

    createTxData(...args: any[]): void;

    delegatecall(...args: any[]): void;

    difficulty(...args: any[]): void;

    div(...args: any[]): void;

    dup(...args: any[]): void;

    eq(...args: any[]): void;

    exp(...args: any[]): void;

    extcodecopy(...args: any[]): void;

    extcodesize(...args: any[]): void;

    gas(...args: any[]): void;

    gaslimit(...args: any[]): void;

    gasprice(...args: any[]): void;

    gt(...args: any[]): void;

    invalid(...args: any[]): void;

    iszero(...args: any[]): void;

    jmp(...args: any[]): void;

    jmpi(...args: any[]): void;

    keccak(...args: any[]): void;

    label(...args: any[]): void;

    log0(...args: any[]): void;

    log1(...args: any[]): void;

    log2(...args: any[]): void;

    log3(...args: any[]): void;

    log4(...args: any[]): void;

    lt(...args: any[]): void;

    mload(...args: any[]): void;

    mod(...args: any[]): void;

    msize(...args: any[]): void;

    mstore(...args: any[]): void;

    mstore8(...args: any[]): void;

    mul(...args: any[]): void;

    mulmod(...args: any[]): void;

    not(...args: any[]): void;

    number(...args: any[]): void;

    or(...args: any[]): void;

    origin(...args: any[]): void;

    pc(...args: any[]): void;

    pop(...args: any[]): void;

    push(...args: any[]): void;

    return(...args: any[]): void;

    returndatacopy(...args: any[]): void;

    returndatasize(...args: any[]): void;

    revert(...args: any[]): void;

    sdiv(...args: any[]): void;

    selfdestruct(...args: any[]): void;

    sgt(...args: any[]): void;

    sha3(...args: any[]): void;

    shor(...args: any[]): void;

    signextend(...args: any[]): void;

    sload(...args: any[]): void;

    slt(...args: any[]): void;

    smod(...args: any[]): void;

    sstore(...args: any[]): void;

    staticcall(...args: any[]): void;

    stop(...args: any[]): void;

    sub(...args: any[]): void;

    swap(...args: any[]): void;

    timestamp(...args: any[]): void;
  }

  export class smt_memdb {
    constructor(...args: any[]);

    get(...args: any[]): void;

    getRoot(...args: any[]): void;

    multiDel(...args: any[]): void;

    multiGet(...args: any[]): void;

    multiIns(...args: any[]): void;

    setRoot(...args: any[]): void;
  }

  export function poseidon(inputs: any): any;

  export function poseidon_slow(inputs: any): any;

  export namespace babyjub {
    const A: any;

    const Base8: any[];

    const D: any;

    const Generator: any[];

    const order: any;

    const p: any;

    const subOrder: any;

    function addPoint(a: any, b: any): any;

    function inCurve(P: any): any;

    function inSubgroup(P: any): any;

    function mulPointEscalar(base: any, e: any): any;

    function packPoint(P: any): any;

    function unpackPoint(_buff: any): any;

    namespace F {
      const R: any;

      const Ri: any;

      const bitLength: number;

      const half: any;

      const m: number;

      const mask: any;

      const n32: number;

      const n64: number;

      const n8: number;

      const negone: any;

      const nqr: any;

      const nqr_to_t: any;

      const one: any;

      const p: any;

      const s: number;

      const sqrt_q: any;

      const sqrt_s: number;

      const sqrt_t: any;

      const sqrt_tm1d2: any;

      const sqrt_z: any;

      const t: any;

      const two: any;

      const type: string;

      const zero: any;

      function add(...args: any[]): void;

      function band(...args: any[]): void;

      function bnot(...args: any[]): void;

      function bor(...args: any[]): void;

      function bxor(...args: any[]): void;

      function div(...args: any[]): void;

      function e(...args: any[]): void;

      function eq(...args: any[]): void;

      function exp(...args: any[]): void;

      function fft(...args: any[]): void;

      function fromRng(...args: any[]): void;

      function fromRprBE(...args: any[]): void;

      function fromRprBEM(...args: any[]): void;

      function fromRprLE(...args: any[]): void;

      function fromRprLEM(...args: any[]): void;

      function geq(...args: any[]): void;

      function gt(...args: any[]): void;

      function idiv(...args: any[]): void;

      function ifft(...args: any[]): void;

      function inv(...args: any[]): void;

      function isZero(...args: any[]): void;

      function land(...args: any[]): void;

      function leq(...args: any[]): void;

      function lnot(...args: any[]): void;

      function lor(...args: any[]): void;

      function lt(...args: any[]): void;

      function mod(...args: any[]): void;

      function mul(...args: any[]): void;

      function mulScalar(...args: any[]): void;

      function neg(...args: any[]): void;

      function neq(...args: any[]): void;

      function normalize(...args: any[]): void;

      function pow(...args: any[]): void;

      function random(...args: any[]): void;

      function shl(...args: any[]): void;

      function shr(...args: any[]): void;

      function sqrt(a: any): any;

      function sqrt_old(...args: any[]): void;

      function square(...args: any[]): void;

      function sub(...args: any[]): void;

      function toRprBE(...args: any[]): void;

      function toRprBEM(...args: any[]): void;

      function toRprLE(...args: any[]): void;

      function toRprLEM(...args: any[]): void;

      function toString(...args: any[]): void;

      namespace FFT {
        const roots: any[][];

        const w: any[];

        const wi: any[];

        function fft(...args: any[]): void;

        function ifft(...args: any[]): void;

        function opMulGF(p0: any, p1: any): any;

        namespace F {
          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const FFT: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const R: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const Ri: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const add: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const band: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const bitLength: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const bnot: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const bor: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const bxor: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const div: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const e: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const eq: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const exp: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const fft: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const fromRng: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const fromRprBE: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const fromRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const fromRprLE: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const fromRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const geq: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const gt: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const half: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const idiv: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const ifft: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const inv: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const isZero: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const land: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const leq: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const lnot: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const lor: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const lt: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const m: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const mask: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const mod: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const mul: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const mulScalar: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const n32: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const n64: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const n8: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const neg: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const negone: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const neq: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const normalize: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const nqr: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const nqr_to_t: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const one: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const p: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const pow: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const random: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const s: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const shl: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const shr: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const sqrt: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const sqrt_old: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const sqrt_q: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const sqrt_s: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const sqrt_t: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const sqrt_tm1d2: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const sqrt_z: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const square: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const sub: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const t: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const toRprBE: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const toRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const toRprLE: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const toRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const toString: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const two: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const type: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.F
          const zero: any;
        }

        namespace G {
          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const FFT: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const R: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const Ri: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const add: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const band: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const bitLength: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const bnot: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const bor: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const bxor: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const div: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const e: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const eq: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const exp: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const fft: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const fromRng: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const fromRprBE: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const fromRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const fromRprLE: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const fromRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const geq: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const gt: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const half: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const idiv: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const ifft: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const inv: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const isZero: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const land: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const leq: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const lnot: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const lor: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const lt: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const m: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const mask: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const mod: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const mul: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const mulScalar: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const n32: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const n64: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const n8: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const neg: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const negone: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const neq: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const normalize: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const nqr: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const nqr_to_t: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const one: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const p: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const pow: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const random: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const s: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const shl: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const shr: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const sqrt: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const sqrt_old: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const sqrt_q: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const sqrt_s: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const sqrt_t: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const sqrt_tm1d2: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const sqrt_z: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const square: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const sub: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const t: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const toRprBE: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const toRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const toRprLE: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const toRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const toString: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const two: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const type: any;

          // Too-deep object hierarchy from circomlibjs.babyjub.F.FFT.G
          const zero: any;
        }
      }
    }
  }

  export namespace eddsa {
    function packSignature(sig: any): any;

    function pruneBuffer(_buff: any): any;

    function prv2pub(prv: any): any;

    function sign(prv: any, msg: any): any;

    function signMiMC(prv: any, msg: any): any;

    function signMiMCSponge(prv: any, msg: any): any;

    function signPoseidon(prv: any, msg: any): any;

    function unpackSignature(sigBuff: any): any;

    function verify(msg: any, sig: any, A: any): any;

    function verifyMiMC(msg: any, sig: any, A: any): any;

    function verifyMiMCSponge(msg: any, sig: any, A: any): any;

    function verifyPoseidon(msg: any, sig: any, A: any): any;
  }

  export namespace mimc7 {
    function getConstants(seed: any, nRounds: any): any;

    function getIV(seed: any): any;

    function hash(_x_in: any, _k: any): any;

    function multiHash(arr: any, key: any): any;

    namespace F {
      const R: any;

      const Ri: any;

      const bitLength: number;

      const half: any;

      const m: number;

      const mask: any;

      const n32: number;

      const n64: number;

      const n8: number;

      const negone: any;

      const nqr: any;

      const nqr_to_t: any;

      const one: any;

      const p: any;

      const s: number;

      const sqrt_q: any;

      const sqrt_s: number;

      const sqrt_t: any;

      const sqrt_tm1d2: any;

      const sqrt_z: any;

      const t: any;

      const two: any;

      const type: string;

      const zero: any;

      function add(...args: any[]): void;

      function band(...args: any[]): void;

      function bnot(...args: any[]): void;

      function bor(...args: any[]): void;

      function bxor(...args: any[]): void;

      function div(...args: any[]): void;

      function e(...args: any[]): void;

      function eq(...args: any[]): void;

      function exp(...args: any[]): void;

      function fft(...args: any[]): void;

      function fromRng(...args: any[]): void;

      function fromRprBE(...args: any[]): void;

      function fromRprBEM(...args: any[]): void;

      function fromRprLE(...args: any[]): void;

      function fromRprLEM(...args: any[]): void;

      function geq(...args: any[]): void;

      function gt(...args: any[]): void;

      function idiv(...args: any[]): void;

      function ifft(...args: any[]): void;

      function inv(...args: any[]): void;

      function isZero(...args: any[]): void;

      function land(...args: any[]): void;

      function leq(...args: any[]): void;

      function lnot(...args: any[]): void;

      function lor(...args: any[]): void;

      function lt(...args: any[]): void;

      function mod(...args: any[]): void;

      function mul(...args: any[]): void;

      function mulScalar(...args: any[]): void;

      function neg(...args: any[]): void;

      function neq(...args: any[]): void;

      function normalize(...args: any[]): void;

      function pow(...args: any[]): void;

      function random(...args: any[]): void;

      function shl(...args: any[]): void;

      function shr(...args: any[]): void;

      function sqrt(a: any): any;

      function sqrt_old(...args: any[]): void;

      function square(...args: any[]): void;

      function sub(...args: any[]): void;

      function toRprBE(...args: any[]): void;

      function toRprBEM(...args: any[]): void;

      function toRprLE(...args: any[]): void;

      function toRprLEM(...args: any[]): void;

      function toString(...args: any[]): void;

      namespace FFT {
        const roots: any[][];

        const w: any[];

        const wi: any[];

        function fft(...args: any[]): void;

        function ifft(...args: any[]): void;

        function opMulGF(p0: any, p1: any): any;

        namespace F {
          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const FFT: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const R: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const Ri: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const add: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const band: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const bitLength: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const bnot: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const bor: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const bxor: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const div: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const e: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const eq: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const exp: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const fft: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const fromRng: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const fromRprBE: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const fromRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const fromRprLE: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const fromRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const geq: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const gt: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const half: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const idiv: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const ifft: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const inv: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const isZero: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const land: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const leq: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const lnot: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const lor: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const lt: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const m: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const mask: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const mod: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const mul: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const mulScalar: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const n32: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const n64: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const n8: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const neg: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const negone: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const neq: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const normalize: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const nqr: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const nqr_to_t: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const one: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const p: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const pow: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const random: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const s: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const shl: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const shr: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const sqrt: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const sqrt_old: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const sqrt_q: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const sqrt_s: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const sqrt_t: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const sqrt_tm1d2: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const sqrt_z: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const square: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const sub: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const t: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const toRprBE: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const toRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const toRprLE: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const toRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const toString: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const two: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const type: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.F
          const zero: any;
        }

        namespace G {
          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const FFT: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const R: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const Ri: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const add: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const band: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const bitLength: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const bnot: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const bor: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const bxor: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const div: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const e: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const eq: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const exp: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const fft: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const fromRng: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const fromRprBE: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const fromRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const fromRprLE: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const fromRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const geq: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const gt: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const half: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const idiv: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const ifft: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const inv: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const isZero: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const land: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const leq: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const lnot: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const lor: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const lt: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const m: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const mask: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const mod: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const mul: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const mulScalar: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const n32: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const n64: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const n8: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const neg: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const negone: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const neq: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const normalize: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const nqr: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const nqr_to_t: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const one: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const p: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const pow: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const random: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const s: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const shl: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const shr: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const sqrt: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const sqrt_old: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const sqrt_q: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const sqrt_s: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const sqrt_t: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const sqrt_tm1d2: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const sqrt_z: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const square: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const sub: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const t: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const toRprBE: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const toRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const toRprLE: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const toRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const toString: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const two: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const type: any;

          // Too-deep object hierarchy from circomlibjs.mimc7.F.FFT.G
          const zero: any;
        }
      }
    }
  }

  export namespace mimc_gencontract {
    const abi: {
      constant: boolean;
      inputs: {
        name: string;
        type: string;
      }[];
      name: string;
      outputs: {
        name: string;
        type: string;
      }[];
      payable: boolean;
      stateMutability: string;
      type: string;
    }[];

    function createCode(seed: any, n: any): any;
  }

  export namespace mimcsponge {
    function getConstants(seed: any, nRounds: any): any;

    function getIV(seed: any): any;

    function hash(_xL_in: any, _xR_in: any, _k: any): any;

    function multiHash(arr: any, key: any, numOutputs: any): any;
  }

  export namespace mimcsponge_gencontract {
    const abi: {
      constant: boolean;
      inputs: {
        name: string;
        type: string;
      }[];
      name: string;
      outputs: {
        name: string;
        type: string;
      }[];
      payable: boolean;
      stateMutability: string;
      type: string;
    }[];

    function createCode(seed: any, n: any): any;
  }

  export namespace pedersenHash {
    function getBasePoint(baseHashType: any, pointIdx: any): any;

    function hash(msg: any, options: any): any;
  }

  export namespace poseidon_gencontract {
    function createCode(nInputs: any): any;

    function generateABI(nInputs: any): any;
  }

  export namespace smt {
    class SMT {
      constructor(...args: any[]);

      delete(...args: any[]): void;

      find(...args: any[]): void;

      insert(...args: any[]): void;

      update(...args: any[]): void;
    }

    class SMTMemDB {
      constructor(...args: any[]);

      get(...args: any[]): void;

      getRoot(...args: any[]): void;

      multiDel(...args: any[]): void;

      multiGet(...args: any[]): void;

      multiIns(...args: any[]): void;

      setRoot(...args: any[]): void;
    }

    function loadFromFile(fileName: any): void;

    function newMemEmptyTrie(): any;
  }

  export namespace smt_hashes_mimc {
    function hash0(left: any, right: any): any;

    function hash1(key: any, value: any): any;

    namespace F {
      const R: any;

      const Ri: any;

      const bitLength: number;

      const half: any;

      const m: number;

      const mask: any;

      const n32: number;

      const n64: number;

      const n8: number;

      const negone: any;

      const nqr: any;

      const nqr_to_t: any;

      const one: any;

      const p: any;

      const s: number;

      const sqrt_q: any;

      const sqrt_s: number;

      const sqrt_t: any;

      const sqrt_tm1d2: any;

      const sqrt_z: any;

      const t: any;

      const two: any;

      const type: string;

      const zero: any;

      function add(...args: any[]): void;

      function band(...args: any[]): void;

      function bnot(...args: any[]): void;

      function bor(...args: any[]): void;

      function bxor(...args: any[]): void;

      function div(...args: any[]): void;

      function e(...args: any[]): void;

      function eq(...args: any[]): void;

      function exp(...args: any[]): void;

      function fft(...args: any[]): void;

      function fromRng(...args: any[]): void;

      function fromRprBE(...args: any[]): void;

      function fromRprBEM(...args: any[]): void;

      function fromRprLE(...args: any[]): void;

      function fromRprLEM(...args: any[]): void;

      function geq(...args: any[]): void;

      function gt(...args: any[]): void;

      function idiv(...args: any[]): void;

      function ifft(...args: any[]): void;

      function inv(...args: any[]): void;

      function isZero(...args: any[]): void;

      function land(...args: any[]): void;

      function leq(...args: any[]): void;

      function lnot(...args: any[]): void;

      function lor(...args: any[]): void;

      function lt(...args: any[]): void;

      function mod(...args: any[]): void;

      function mul(...args: any[]): void;

      function mulScalar(...args: any[]): void;

      function neg(...args: any[]): void;

      function neq(...args: any[]): void;

      function normalize(...args: any[]): void;

      function pow(...args: any[]): void;

      function random(...args: any[]): void;

      function shl(...args: any[]): void;

      function shr(...args: any[]): void;

      function sqrt(a: any): any;

      function sqrt_old(...args: any[]): void;

      function square(...args: any[]): void;

      function sub(...args: any[]): void;

      function toRprBE(...args: any[]): void;

      function toRprBEM(...args: any[]): void;

      function toRprLE(...args: any[]): void;

      function toRprLEM(...args: any[]): void;

      function toString(...args: any[]): void;

      namespace FFT {
        const roots: any[][];

        const w: any[];

        const wi: any[];

        function fft(...args: any[]): void;

        function ifft(...args: any[]): void;

        function opMulGF(p0: any, p1: any): any;

        namespace F {
          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const FFT: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const R: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const Ri: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const add: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const band: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const bitLength: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const bnot: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const bor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const bxor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const div: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const e: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const eq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const exp: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const fft: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const fromRng: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const fromRprBE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const fromRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const fromRprLE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const fromRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const geq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const gt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const half: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const idiv: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const ifft: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const inv: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const isZero: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const land: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const leq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const lnot: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const lor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const lt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const m: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const mask: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const mod: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const mul: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const mulScalar: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const n32: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const n64: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const n8: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const neg: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const negone: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const neq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const normalize: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const nqr: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const nqr_to_t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const one: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const p: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const pow: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const random: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const s: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const shl: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const shr: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const sqrt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const sqrt_old: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const sqrt_q: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const sqrt_s: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const sqrt_t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const sqrt_tm1d2: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const sqrt_z: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const square: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const sub: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const toRprBE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const toRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const toRprLE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const toRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const toString: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const two: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const type: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.F
          const zero: any;
        }

        namespace G {
          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const FFT: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const R: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const Ri: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const add: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const band: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const bitLength: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const bnot: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const bor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const bxor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const div: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const e: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const eq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const exp: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const fft: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const fromRng: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const fromRprBE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const fromRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const fromRprLE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const fromRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const geq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const gt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const half: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const idiv: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const ifft: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const inv: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const isZero: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const land: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const leq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const lnot: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const lor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const lt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const m: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const mask: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const mod: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const mul: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const mulScalar: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const n32: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const n64: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const n8: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const neg: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const negone: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const neq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const normalize: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const nqr: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const nqr_to_t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const one: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const p: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const pow: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const random: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const s: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const shl: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const shr: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const sqrt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const sqrt_old: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const sqrt_q: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const sqrt_s: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const sqrt_t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const sqrt_tm1d2: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const sqrt_z: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const square: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const sub: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const toRprBE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const toRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const toRprLE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const toRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const toString: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const two: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const type: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_mimc.F.FFT.G
          const zero: any;
        }
      }
    }
  }

  export namespace smt_hashes_poseidon {
    function hash0(left: any, right: any): any;

    function hash1(key: any, value: any): any;

    namespace F {
      const R: any;

      const Ri: any;

      const bitLength: number;

      const half: any;

      const m: number;

      const mask: any;

      const n32: number;

      const n64: number;

      const n8: number;

      const negone: any;

      const nqr: any;

      const nqr_to_t: any;

      const one: any;

      const p: any;

      const s: number;

      const sqrt_q: any;

      const sqrt_s: number;

      const sqrt_t: any;

      const sqrt_tm1d2: any;

      const sqrt_z: any;

      const t: any;

      const two: any;

      const type: string;

      const zero: any;

      function add(...args: any[]): void;

      function band(...args: any[]): void;

      function bnot(...args: any[]): void;

      function bor(...args: any[]): void;

      function bxor(...args: any[]): void;

      function div(...args: any[]): void;

      function e(...args: any[]): void;

      function eq(...args: any[]): void;

      function exp(...args: any[]): void;

      function fft(...args: any[]): void;

      function fromRng(...args: any[]): void;

      function fromRprBE(...args: any[]): void;

      function fromRprBEM(...args: any[]): void;

      function fromRprLE(...args: any[]): void;

      function fromRprLEM(...args: any[]): void;

      function geq(...args: any[]): void;

      function gt(...args: any[]): void;

      function idiv(...args: any[]): void;

      function ifft(...args: any[]): void;

      function inv(...args: any[]): void;

      function isZero(...args: any[]): void;

      function land(...args: any[]): void;

      function leq(...args: any[]): void;

      function lnot(...args: any[]): void;

      function lor(...args: any[]): void;

      function lt(...args: any[]): void;

      function mod(...args: any[]): void;

      function mul(...args: any[]): void;

      function mulScalar(...args: any[]): void;

      function neg(...args: any[]): void;

      function neq(...args: any[]): void;

      function normalize(...args: any[]): void;

      function pow(...args: any[]): void;

      function random(...args: any[]): void;

      function shl(...args: any[]): void;

      function shr(...args: any[]): void;

      function sqrt(a: any): any;

      function sqrt_old(...args: any[]): void;

      function square(...args: any[]): void;

      function sub(...args: any[]): void;

      function toRprBE(...args: any[]): void;

      function toRprBEM(...args: any[]): void;

      function toRprLE(...args: any[]): void;

      function toRprLEM(...args: any[]): void;

      function toString(...args: any[]): void;

      namespace FFT {
        const roots: any[][];

        const w: any[];

        const wi: any[];

        function fft(...args: any[]): void;

        function ifft(...args: any[]): void;

        function opMulGF(p0: any, p1: any): any;

        namespace F {
          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const FFT: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const R: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const Ri: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const add: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const band: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const bitLength: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const bnot: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const bor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const bxor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const div: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const e: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const eq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const exp: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const fft: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const fromRng: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const fromRprBE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const fromRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const fromRprLE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const fromRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const geq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const gt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const half: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const idiv: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const ifft: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const inv: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const isZero: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const land: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const leq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const lnot: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const lor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const lt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const m: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const mask: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const mod: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const mul: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const mulScalar: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const n32: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const n64: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const n8: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const neg: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const negone: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const neq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const normalize: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const nqr: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const nqr_to_t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const one: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const p: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const pow: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const random: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const s: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const shl: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const shr: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const sqrt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const sqrt_old: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const sqrt_q: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const sqrt_s: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const sqrt_t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const sqrt_tm1d2: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const sqrt_z: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const square: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const sub: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const toRprBE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const toRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const toRprLE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const toRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const toString: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const two: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const type: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.F
          const zero: any;
        }

        namespace G {
          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const FFT: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const R: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const Ri: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const add: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const band: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const bitLength: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const bnot: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const bor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const bxor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const div: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const e: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const eq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const exp: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const fft: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const fromRng: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const fromRprBE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const fromRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const fromRprLE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const fromRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const geq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const gt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const half: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const idiv: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const ifft: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const inv: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const isZero: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const land: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const leq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const lnot: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const lor: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const lt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const m: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const mask: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const mod: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const mul: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const mulScalar: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const n32: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const n64: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const n8: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const neg: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const negone: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const neq: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const normalize: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const nqr: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const nqr_to_t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const one: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const p: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const pow: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const random: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const s: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const shl: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const shr: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const sqrt: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const sqrt_old: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const sqrt_q: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const sqrt_s: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const sqrt_t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const sqrt_tm1d2: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const sqrt_z: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const square: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const sub: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const t: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const toRprBE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const toRprBEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const toRprLE: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const toRprLEM: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const toString: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const two: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const type: any;

          // Too-deep object hierarchy from circomlibjs.smt_hashes_poseidon.F.FFT.G
          const zero: any;
        }
      }
    }
  }
}
